spring:
  datasource:
    url: jdbc:mysql://localhost:3306/knowledge?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: root #3862441ll
mybatis:
  mapper-locations: classpath:mapper/rh/study/knowledge/dao/**/*.xml
  type-aliases-package: rh.study.knowledge.entity
  configuration:
    #驼峰命名规范 如：数据库字段是  order_id 那么 实体字段就要写成 orderId
    map-underscore-to-camel-case: true
# 如果想看到mybatis日志需要做如下配置
logging:
  level:
    com:
      battcn: DEBUG
########## 通用Mapper ##########
# 主键自增回写方法,默认值MYSQL,详细说明请看文档
mapper:
  identity: MYSQL
  mappers: tk.mybatis.mapper.common.BaseMapper
# 设置 insert 和 update 中，是否判断字符串类型!=''
  not-empty: true
# 枚举按简单类型处理
  enum-as-simple-type: true
########## 分页插件 ##########
pagehelper:
#分页插件会自动检测当前的数据库链接，自动选择合适的分页方式。
  helper-dialect: mysql
  #为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值， 可以配置 pageNum,pageSize,count,pageSizeZero,reasonable，不配置映射的用默认值， 默认值为pageNum=pageNum。
  params: count=countSql
  #分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页。默认false 时，直接根据参数进行查询。
  reasonable: true
  #支持通过 Mapper 接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。
  support-methods-arguments: true

ht_username: admin
ht_password: Admin@123